### ISSUE TITLE
[FEATURE] Footer

### ISSUE THREAD

**Issue by SeoMiYoung** [LikeLion-FE-React-Project04/project-repo#10]
# 🌳 작업 브랜치
feat/#10

# 📝 TASK 개요
- 메인페이지의 Footer를 완성합니다

# ✅ To Do 및 진행상황
- [x] Footer영역 마크업하기
- [x] Footer영역 스타일(scss) 적용하기
- [x] Footer영역 React Router를 사용해서 링크연결하기
- [x] 외부링크 연결해주기 (블로그, 인스타그램, 네이버 포스트, 페이스북, 유튜브)
- [x] 웹접근성 고려하기
