### ISSUE TITLE
[FEATURE] 오늘 하루 안보기 모달창 구현하기

### ISSUE THREAD

**Issue by SeoMiYoung** [LikeLion-FE-React-Project04/project-repo#11]
# 🌳 작업 브랜치
feat/#11

# 📝 TASK 개요
- 쿠키설정으로 오늘 하루 안보기 모달을 완성합니다

# ✅ To Do 및 진행상황
- [x] 마크업 및 CSS(scss)완성
- [x] 닫기 버튼 JS구현
- [x] 오늘 하루 안보기 버튼 JS구현
- [x] 파일을 조금씩 여러파일로 분리해서 관리하기
