### ISSUE TITLE
[FEATURE] CartModal 컴포넌트 개발

### ISSUE THREAD

**Issue by SeoMiYoung** [LikeLion-FE-React-Project04/project-repo#15]
# 🌳 작업 브랜치
feat/#15

# 📝 TASK 개요
**CartModal 컴포넌트 개발**
- 상품카드의 장바구니 버튼을 클릭하면 모달 띄우기
- 스토어 구축 및 AtomFamily 활용
- Counter 컴포넌트 활용, Button 컴포넌트 활용
- AtomFamily로 받은 데이터와 Counter의 Atom을 활용해서 전체 가격 계산
- 장바구니 담기 버튼 클릭 시 상품과 개수를 저장 (localstorage를 사용할지 recoil를 사용할 지는 아직 미정 )
- 모달 띄울시 모달을 제외한 나머지 배경 어둡게 만들기

# ✅ To Do 및 진행상황
- [x] 컴포넌트 마크업 구축
- [x] Atom을 통한 데이터 연동
- [x] Counter를 통한 전체 가격 계산
- [x] 장바구니 담기 버튼 로직 구현
- [x] 다크 필터 구현
