### ISSUE TITLE
[FEATURE] ProductThumbnail 컴포넌트 로직 구현

### ISSUE THREAD

**Issue by ssw6750** [LikeLion-FE-React-Project04/project-repo#156]
# 🌳 작업 브랜치
feat/#103

# 📝 TASK 개요
**ProductThumbnail 컴포넌트 로직 구현**

# ✅ To Do 및 진행상황
- [x] prams로 받은 id에 맞게 상품데이터를 뿌려줌
- [x] Counter 컴포넌트 로직 구현
- [x] 장바구니 담기 버튼 누를시 장바구니 로직 구현
