### ISSUE TITLE
[FEATURE] 슬라이더(swiper) 웹접근성 리팩토링

### ISSUE THREAD

**Issue by ssw6750** [LikeLion-FE-React-Project04/project-repo#202]
# 📝 TASK 개요
**슬라이더(swiper) 웹접근성 준수하여 리팩토링**

**Slide 구현 시 웹 접근성을 준수하려면 고려해야 하는 것들**
1. 슬라이드의 이전, 다음 **버튼이 있어 키보드로** 이전, 다음 슬라이드의 **접근이 가능**해야 한다.
2. 총 몇 장의 슬라이드 중 현재 활성화된 슬라이드가 몇 번째 슬라이드 인지 확인 할 수 있는 **인디게이터**가 있어야 한다.
3. **자동 재생 슬라이드 일 경우 정지 버튼을 포함**하고 있어야 한다.
4. 키보드 tab, back tab으로 **모든 슬라이드 접근**이 가능하여야 한다.
5. 무한 루프 형식의 슬라이드는 해당 슬라이드에서 포커스가 벗어날 수 없으면 웹 접근성에 위배된다. (무한 루프 옵션을 사용 시 키보드 탭 동작 또는 화살표 키 동작으로 해당 영역을 벗어날 수 있는지 확인 필요. 없다면 별도로 작업해주어야 함 - **현재 프로젝트는 해당사항 없음**)

### 메인 캐로셀
**기존 컬리사이트의 메인 캐로셀 문제점**
1. 버튼에 접근할 수 없다.
2. 배너에 대한 설명도 매우 부족하다.
3. 자동 재생이지만 정지 버튼이 존재하지 않는다
![기존 컬리 메인캐로셀](https://user-images.githubusercontent.com/73629761/229492331-24d48e5e-a55d-4409-8fe5-0c390e706ace.gif)

**프로젝트 칼리의 메인캐로셀**은 해당 문제를 모두 해결했다.
![메인캐로셀-웹접근성](https://user-images.githubusercontent.com/73629761/229492587-1d7e6ade-1bc9-4059-9489-853ff446e927.gif)

# ✅ To Do 및 진행상황
### 메인 캐로셀
- [x] 슬라이더 버튼 접근
- [x] 슬라이더 인디게이터
- [x] 자동 재생 접근성
- [x] 탭 접근성

### 상품 캐로셀
- [ ] 슬라이더 버튼 접근
- [ ] 슬라이더 인디게이터
- [ ] 자동 재생 접근성
- [ ] 탭 접근성
