### ISSUE TITLE
[FEATURE] 장바구니 모달 웹접근성 리팩토링

### ISSUE THREAD

**Issue by ssw6750** [LikeLion-FE-React-Project04/project-repo#206]
# 📝 TASK 개요
**장바구니 모달 웹접근성 리팩토링**

💡 모달창은 다음과 같은 웹접근성 요구사항을 충족시켜야 합니다.

1. 모달창이 열릴 때, 초점이 모달창 내부에 위치해야 합니다.
2. 모달창 내부에서 탭 키를 이용하여 초점을 순환할 수 있어야 합니다.
3. 모달창이 열릴 때, 스크린리더 사용자에게 모달창이 열렸음을 알리는 역할을 해야 합니다.
4. 모달창이 닫힐 때, 초점이 모달창 이외의 위치에 위치해야 합니다.

실제 컬리사이트의 장바구니 모달의 웹접근성
![zzz](https://user-images.githubusercontent.com/73629761/229977179-5aee9925-2588-4662-805d-7991daa8b779.gif)

프로젝트 칼리의 장바구니 모달의 웹접근성
![칼리-모달 웹접근성](https://user-images.githubusercontent.com/73629761/230128349-67d80bb4-42aa-4a70-92d3-b79313d1489b.gif)

**- 개선된 점**: 모달이 열릴시 스크린리더가 알려준다.
**- 보완해야 할 점**: 내용이 2번씩 읽힌다.

# ✅ To Do 및 진행상황
- [x] 초점 내부 이동
- [x] 탭키 순환
- [x] 모달 알림
- [x] 모달 창 닫힐 시 외부로 초점 이동
---
- [x] 모달 외부 클릭 시 포커싱이 빠져 나가는 버그 수정
