### ISSUE TITLE
[REFACTORING] 회원가입 페이지 리팩토링

### ISSUE THREAD

**Issue by ssw6750** [LikeLion-FE-React-Project04/project-repo#215]
# 📝 TASK 개요
 회원가입 페이지 리팩토링
- https://github.com/LikeLion-FE-React-Project04/project-repo/issues/253
- https://github.com/LikeLion-FE-React-Project04/project-repo/issues/248
## 회원가입 상태 관리
- 회원가입 폼 입력값이 저장되는 아톰
```
export const signUpFormState = atom({
  key: 'signUpFormState',
  default: {
    name: '',
    email: '',
    password: '',
    passwordConfirm: '',
    phoneNumber: '',
    address: '',
    gender: 'non',
    birth: {
      year: '',
      month: '',
      day: '',
    },
  },
});
```

- 회원가입 폼의 유효성 검사 결과 값이 저장되는 아톰
```
export const formValidationState = atom({
  key: 'formValidationState',
  default: {
    name: '',
    email: '',
    password: '',
    passwordConfirm: '',
    phoneNumber: '',
    address: '',
    gender: '',
    birth: '',
  },
});
```

- 이메일 중복확인 여부 값이 저장되는 아톰
```
export const emailConfirmState = atom({
  key: 'emailConfirmState',
  default: false,
});
```

- 약관동의 체크 여부 값이 저장되는 아톰
```
export const agreementState = atom({
  key: 'agreementState',
  default: {
    ag1: false,
    ag2: false,
    ag3: false,
    ag4: false,
  },
});
```

- 필수 약관동의를 전부 체크했는지 확인하는 셀렉터
```
export const agreementEssentialState = selector({
  key: 'agreementEssentialState',
  get: ({ get }) => {
    const agreement = get(agreementState);
    const { ag1, ag2, ag4 } = agreement;

    return ag1 && ag2 && ag4;
  },
});
```

## 1. 유효성 검사
**유효성 검사가 발생 조건**
- Input 요소 입력시 (onChange)
- 이메일 중복확인 버튼 누를 시
- 회원가입 버튼 누를시

**사용되는 유효성 검사**
| 타입 | 유효성 검사 |
|---|---|
|이메일|"tmp@tmp.com" 형식 입력|
|비밀번호|최소 10자리 이상 입력|
||영문/숫자/특수문자(공백 제외)만 허용하며, 2개 이상 조합|
|비밀번호 확인|비밀번호와 동일한 비밀번호를 입력|
|이름|2자리 이상 입력|
|주소|카카오 주소로 입력|
|휴대폰|11자리 숫자 |
|성별|기본: 선택 안함 |
|생년월일|날짜 형식 입력 |

- 유효성 검사 유틸함수 `checkValidation`는 `type`에 맞게 유효성 검사 로직을 수행합니다. 유효성 검사를 통과하지 못할시 해당하는 `경고 문구`를 return합니다. 통과할 경우 `''`를 return 합니다. 
```
export function checkValidation(type, value) {
  switch (type) {
    case 'email': {
      const email_validation =
        /^[0-9a-zA-Z]([-_\.]?[0-9a-zA-Z])*@[0-9a-zA-Z]([-_\.]?[0-9a-zA-Z])*\.[a-zA-Z]{2,3}$/i;

      if (!value) {
        return '이메일을 입력해주세요';
      } else if (!email_validation.test(value)) {
        return '이메일 형식으로 입력해주세요';
      } else {
        return '';
      }
    }
    case 'password': {
      const password_validation_count = /^.{10,}$/;
      const password_validation_format =
        /^(?!((?:[A-Za-z]+)|(?:[~!@#$%^&*()_+=]+)|(?:[0-9]+))$)[A-Za-z\d~!@#$%^&*()_+=]{10,}$/;

      if (!value || !password_validation_count.test(value)) {
        return '이메일을 최소 10자리 이상 입력해주세요.';
      } else if (!password_validation_format.test(value)) {
        return '영문/숫자/특수문자(공백 제외)만 허용하며, 2개 이상 조합';
      } else {
        return '';
      }
    }
   ...
  }
}
```
- 폼 요소에 입력이 발생할 떄 마다 유효성을 체크하여 저장합니다.
- 저장된 경고 문구는 폼요소 하단, 또는 경고 창으로 표시됩니다..
```
// 인풋 요소의 name 과 value로 유효성 체크하는 로직
  const InputValidation = (name, value) => {
    const pragment = checkValidation(name, value);

    // 유효성 검사
    setFormValidation((prev) => {
      const tmp = { ...prev };

      tmp[name] = pragment;

      return tmp;
    });
  };

  // 회원가입 인풋 요소 변경시 작동하는 유효성 검사 함수
  const handleChangeInput = (e) => {
    let { name, value } = e.target;

    // 폼데이터 저장
    setSignUpForm((prev) => {
      const tmp = { ...prev };

      tmp[name] = value;

      return tmp;
    });

    if (name == 'email') {
      setEmailConfirm(false);
    }

    if (name == 'password') {
      InputValidation('passwordConfirm', [signUpForm.passwordConfirm, value]);
    }

    if (name == 'passwordConfirm') {
      value = [value, signUpForm.password];
    }

    InputValidation(name, value);
  };
```
## 2. 이메일 중복 검사
이메일의 유효성 검사 후, 통과 시 해당 이메일에 대한 쿼리문을 보냅니다.
사용 가능한 이메일 이라면 `setEmailConfirm()`을 이용하여 이메일 확인 상태(`emailConfirmState`)를 true로 변경합니다.
이메일 확인 상태는 이메일 `from` 입력 시 다시 `false`로 바뀝니다.
이메일 확인 상태가 `true`일시 이메일 확인 버튼이 비활성화 됩니다.
```
  const confirmEmail = useCallback(
    async ({ email } = signUpForm) => {
      // 유효성 확인
      // 통과시 '' 반환
      let alertPragment = checkValidation('email', email);

      // 이미 존재하는 이메일인지 확인
      if (alertPragment == '') {
        const q = query(
          collection(db, 'users'),
          where('email', '==', signUpForm.email)
        );
        const querySnapshot = await getDocs(q);
        let isExist = false;

        querySnapshot.forEach((doc) => {
          isExist = true;
        });
        setEmailConfirm(!isExist);
        alertPragment = isExist
          ? '이미 존재하는 이메일입니다.'
          : '사용 가능한 이메일 입니다.';
      }

      showAlertBox({
        alertText: alertPragment, 
        btnUiType: 'onlyConfirm', 
      });
    },
    [signUpForm]
  );
```

## 3. 회원가입 
회원가입 버튼을 누를시 회원가입이 진행됩니다.
`signUpValidation`을 통해 한번 더 유효성 검사를 진행하고, 문제가 있을 시 경고를 띄웁니다.
유효성 검사를 통과하면 `agreementEssential`를 통해 필수 약관 동의를 확인합니다.
모두 통과 시  `signUp`훅 을 통해 `파이어베이스`에 계정을 생성하고, 생성한 계정의 정보를 `createAuthUser`훅을 통해 `파이어스토어`에 등록합니다.

```
const signUpSubmit = useCallback(
    async ({
      name,
      email,
      password,
      phoneNumber,
      gender,
      birth,
    } = signUpForm) => {
      // 유효성 검사 실행
      // 통과 시 '' 리턴
      const message = signUpValidation();

      // 미통과 (경고 알람)
      if (message) {
        showAlertBox({
          alertText: message,
          btnUiType: 'onlyConfirm', // (필수) [버튼 형태 설정] 확인 버튼만 있는 'onlyConfirm' 또는, 확인/취소 버튼이 있는 'confirmAndCancel'을 넣어주기
        });

        return;
      }

      // 유효성 검사 통과. but 필수 이용약관 동의 x
      if (!agreementEssential) {
        showAlertBox({
          alertText: '이용약관을 확인해주세요.',
          btnUiType: 'onlyConfirm',
        });

        return;
      }

      // 전부 통과하면 계정 생성
      const user = await signUp(email, password, name, birth);

      createAuthUser(user, {
        phoneNumber,
        address,
        gender,
        birth,
      });

      showAlertBox({
        alertText: '회원가입이 완료되었습니다.',
        moveUrl: '/',
        btnUiType: 'onlyConfirm',
      });

      return;
    },
    [signUpForm, emailConfirm, address, agreementEssential]
  );

```

**구현 gif**
![회원가입-유효성](https://user-images.githubusercontent.com/73629761/231751845-52e55642-bcea-42db-8cc3-f7b4ba064f5e.gif)

### 2. 약관 동의
유효성 검사 통과 후 **필수 약관을 모두 동의** 해야지만 회원가입 성공

**구현 gif**
![회원가입-이용약관](https://user-images.githubusercontent.com/73629761/231753065-cfc4273c-293b-4976-a355-389f381eec7e.gif)

### 4. 커스텀 훅 분리 및 최적화

# ✅ To Do 및 진행상황
- [x] Input 컴포넌트 파일 위치 변경
- [x] RadioButton 컴포넌트 수정
- [x] CheckBox 컴포넌트 구현
---
- [x] (이메일, 비밀번호, 비밀번호 확인, 이름, 휴대폰 )유효성 검사
- [x] 성별 확인 (Gender 컴포넌트)
- [x] 생년월일 확인 (Birth 컴포넌트)
- [x] 주소 확인 (SignUpAddress 컴포넌트)
- [x] 약관 동의 (Agreement 컴포넌트)
- [x] 이메일 중복 버튼
---
- [x] 컴포넌트 분리
- [x] 커스텀 훅 분리(유효성 검사, 회원가입 요청, 이메일 확인)
- [x] 유효성 검사 유틸함수
- [x] 회원가입 데이터 상태관리
