### ISSUE TITLE
[FEATURE] 상품 디테일 메뉴 탭 구현

### ISSUE THREAD

**Issue by ssw6750** [LikeLion-FE-React-Project04/project-repo#225]
# 📝 TASK 개요
**상품 디테일 메뉴 탭 구현**
해당 git 참고
![상품 디테일 메뉴 탭](https://user-images.githubusercontent.com/73629761/231352319-cf51c202-ebb2-4080-901b-b61f89100d18.gif)

## [해결] 상품정보, 상세정보, 후기, 문의 글 누를시 해당 영역으로 이동
[scrollIntoView](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView)를 사용하면 특정 element를 기준으로 스크롤을 이동시킬 수 있습니다.
`scrollIntoView()`를 사용하여 커스텀 훅 `useMoveScroll()`을 구현하였습니다. 
```
export default function useMoveScroll(name) {
  const element = useRef();
  const onMoveToElement = () => {
    element.current?.scrollIntoView({ behavior: 'smooth', block: 'start' });
  };

  return { element, onMoveToElement, name };
}
```

배열의 형태로 `useMoveScroll()`를 불러옵니다.
```
  const navigations = [
    useMoveScroll('상품 정보'),
    useMoveScroll('상세 정보'),
    useMoveScroll('리뷰'),
    useMoveScroll('상품 문의'),
  ];
```

네비게이션으로 이동되는 영역들을 배열로 관리합니다.
배열을 `map`으로 돌면서 각각의 영역들을 `div`로 감싼후 해당 `div의 ref`를 `useMoveScroll의 element`에 연결합니다.
```
  const navigationParts = [
    <ProductInformation key={0} product={product} />,
    <DetailInformation key={1} product={product} />,
    <ProductReview key={2} />,
    <ProductInquiry key={3} />,
  ];

  const navigationPartRefs = navigationParts.map((part, index) => (
    <div
      ref={navigations[index].element}
      key={index}
      className={styles.naviLayout}
    >
      {part}
    </div>
  ));
```
`ProductDetailMenu` 컴포넌트에 `props`로 `navigations`를 넘겨줍니다.
받은 **navigations**를 `map`으로 돌면서 `onMoveToElement` 이벤트를 걸어주고 `name`을 표시합니다.
```
  const menuTabs = navigations.map((tab, index) => {
    return (
      // eslint-disable-next-line react/jsx-key
      <li>
        <button
          ref={(el) => (naviRef.current[index] = el)}
          onClick={(e) => {
            InitFocusing();
            e.target.classList.add(styles.Active);
            tab.onMoveToElement();
          }}
        >
          {tab.name}
        </button>
      </li>
    );
  });
```
[추가] 선택된 네비게이션 표시를 `className={styles.Active}`로 표시합니다. 따라서 네비게이션이 클릭되면 `Active`를 모두 지우는 `InitFocusing()`을 먼저 수행합니다. - 
```
  const naviRef = useRef([]);

  function InitFocusing() {
    naviRef.current.forEach((ref) => {
      ref.classList.remove(styles.Active);
    });
  }
```
다른 코드로 수정되었음
## [해결] 스크롤 내릴 시 헤더 아래로 위치 고정
다음은 ```ProductDetailMenu.module.scss```의 코드입니다.
```
.productDetailMenu {
  // 네비 상단에 고정
  position: sticky;
  top: 66px;
  z-index: 50;
}
```
네비를 작은헤더 밑에 고정시키기 위해 위와 같은 코드를 추가시켰습니다.
참고로 66px은 작은헤더의 height를 고려해서 넣은 값입니다.

## [해결] 네비게이션바의 후기탭에 현재 후기의 개수가 업데이트되게 한다
다음은 ```ProductDetail.jsx```의 코드입니다.
```
import { useDetailCollection } from '../../firebase/firestore/useDetailCollection';
```
```
//후기 개수 navigation바에 업데이트
const [count, setCount] = useState(0);
const { dataState } = useDetailCollection('reviewData');
const [countText, setCountText] = useState('');

useEffect(() => {
   if (dataState) {
      setCount(dataState.length);
   }
   let text = `후기(${count})`;
   setCountText(text);
}, [dataState, count]);
```
useDetailCollection이라는 함수를 호출합니다. useDetailCollection은 특정 상품에 해당하는 후기 데이터들을 하나의 배열로 묶어서 반환해주는 함수입니다. 따라서, dataState의 length를 구함으로써, 특정 상품에 대한 후기 데이터들이 몇개인지 알 수 있습니다. 후기개수에 변동이 생길때마다 다시 랜더링을 시키기 위해서, 후기의 개수는 useState의 count로 관리했습니다.

참고로 countText에 저장된 텍스트는, 아래 코드 부분에서 사용됩니다.
```
const navigations = [
  useMoveScroll('상품정보'),
  useMoveScroll('상세정보'),
  useMoveScroll(countText),
  useMoveScroll('문의'),
];
```

## [미해결] 스크롤 이동에 따른 탭스타일 변경
```
  const [position, setPosition] = useState();

  const getElementPosition = (e) => {
    const productInfo = navigations[0].element.current;
    const detailInfo = navigations[1].element.current;
    const review = navigations[2].element.current;
    const inquiry = navigations[3].element.current;

    const scrollY = window.scrollY; // 스크롤 양

    if (scrollY > inquiry.offsetTop - 10) {
      setPosition('inquiry');
    } else if (
      scrollY <= inquiry.offsetTop - 10 &&
      scrollY > review.offsetTop - 10
    ) {
      setPosition('review');
    } else if (
      scrollY <= review.offsetTop - 10 &&
      scrollY > detailInfo.offsetTop - 10
    ) {
      setPosition('detailInfo');
    } else if (
      scrollY <= detailInfo.offsetTop - 10 &&
      scrollY > productInfo.offsetTop - 10
    ) {
      setPosition('productInfo');
    } else {
      setPosition(null);
    }
  };
```
**버그 발생 지점**
```
  // 클린업을 넣어야 하는가요? 넣으면 Cannot read properties of null (reading 'removeEventListener') 에라 발생합니다
  useEffect(() => {
    detailsRef.current.addEventListener('scroll', getElementPosition); // 스크롤시 getBannerPosition 발생

    // return () =>
    //   detailsRef.current.removeEventListener('scroll', getElementPosition); // 클린업, 페이지를 나가면 이벤트 삭제
  }, [detailsRef]);
```
`ProductDetailMenu` 컴포넌트에서 `props`로 `position`을 받음
```
  useEffect(() => {
    InitFocusing();
    if (position) {
      naviRef.current[naviArr.indexOf(position)].classList.add(styles.Active);
    }
  }, [position]);
```

## [해결] 디테일페이지의 네비게이션바 버튼 포커스 스타일 관련 버그
관련 이슈를 참고해주세요.
- https://github.com/LikeLion-FE-React-Project04/project-repo/issues/300

# ✅ To Do 및 진행상황
- [x] 스크롤 내릴 시 헤더 아래로 위치 고정
- [ ] 스크롤 이동에 따른 탭스타일 변경
- [x] 상품정보, 상세정보, 후기, 문의 글 누를시 해당 영역으로 이동
- [x] 네비게이션바의 후기탭에 현재 후기의 개수가 업데이트되게 한다
