### ISSUE TITLE
[REFACTOR] Header -  웹 접근성 피드백 내용 수정

### ISSUE THREAD

**Issue by PracticeKJY** [LikeLion-FE-React-Project04/project-repo#236]
# 🌳 작업 브랜치
`refactoring/#236`

# 📝 TASK 개요
- alt 속성의 대체 텍스트 내용 수정
- 제품 이름 명시
- input과 label 연결하기

# ✅ To Do 및 진행상황
- [x] alt 속성의 대체 텍스트 내용 수정
- [x] 제품 이름 명시
- [x] input과 label 연결하기
