### ISSUE TITLE
[FEATURE] Footer 웹접근성 고려하기

### ISSUE THREAD

**Issue by SeoMiYoung** [LikeLion-FE-React-Project04/project-repo#238]
# 🌳 작업 브랜치
feat/#238

# 📝 TASK 개요
슬비쌤의 웹접근성 피드백을 바탕으로 수정했습니다.

# ✅ To Do 및 진행상황
- [x] '컬리'대신 '칼리'로 바꾸기 (디테일 신경)
- [x] a태그 안에 이미지가 있을 경우, a태그에 aria-label을 주기보다는, 이미지에 alt/aria-label를 주기
- [x] aria-label="인재채용 정보 확인" 이런식으로 쓰기 보다는 더 간결하게 aria-label="인재채용 정보" 이렇게 쓰기
