### ISSUE TITLE
[FEATURE] 상품 문의

### ISSUE THREAD

**Issue by SeoMiYoung** [LikeLion-FE-React-Project04/project-repo#96]
# 🌳 작업 브랜치
feat/#96

# 📝 TASK 개요

# ✅ To Do 및 진행상황
- [x] 문의/리뷰 팝업창 마크업 및 CSS
- [x] placeholder가 보여지다가, 사용자가 글을 쓰려고 클릭하면 입력할 수 있게 초점가기
- [x] 팝업창에서 inquiry와 review 상황에 따른 다른 placeholder가 보여지게 하기
- [x] 글자수 관리
- [x] 사용자가 글자를 무언가 입력했을 경우 placeholder가 다시 띄워지지 않게 하기
